const colorHuntTheme = {
  bg: "#EDE9E6",
  surface: "#F7F3EF",
  surface2: "#E4DDD8",
  surface3: "#D7C9BE",
  border: "#CDBFB5",
  border2: "#9F8B80",
  accent: "#C9996B",
  accent2: "#5C766D",
  accent_dim: "#E6D2BF",
  gold: "#C9996B",
  green: "#5C766D",
  red: "#A65F55",
  purple: "#7B635B",
  text: "#2F2926",
  text2: "#5C4F4A",
  text3: "#7A6D67",
  row_a: "#F7F3EF",
  row_b: "#E8E1DC",
  row_sel: "#D9C2AB",
  row_hdr: "#5C4F4A",
  sidebar_w: 230,
};

const tpkFields = ["Nama Pelanggan", "Keterangan Barang", "No. Faktur", "Tgl Faktur", "Kuantitas", "Harga Satuan", "Unit 1 Barang"];
const dlmFields = ["No. Faktur", "Tgl Faktur", "Nama Pemasok", "Nilai Faktur"];

function trialInfo() {
  return {
    plan: "Trial",
    status: "trial",
    limit: 10,
    used: 0,
    remaining: 10,
    pricing_url: "/#pricing",
    locked_features: ["doc_lain_masukan", "spt_dokumen_lain"],
  };
}

export function emptyState() {
  return {
    raw_headers: [],
    raw_preview: [],
    raw_row_count: 0,
    mapping: {},
    src_filename: "",
    processed: [],
    dup_map: {},
    faktur_rows: [],
    date_diagnostics: { majority_month: "", invalid_indices: [], outlier_indices: [], problem_indices: [], warnings: [], blockers: [] },
    detail_rows: [],
    totals: {},
    dlm: {
      raw_headers: [],
      raw_preview: [],
      raw_row_count: 0,
      mapping: {},
      src_filename: "",
      processed: [],
      totals: {},
      company_npwp: "",
    },
    sdl: {
      processed: [],
      totals: {},
      company_npwp: "",
      tax_period_month: 0,
      tax_period_year: 0,
    },
    subscription: trialInfo(),
  };
}

export function bootstrapData() {
  return {
    themes: { "Color Hunt": colorHuntTheme },
    theme_names: ["Color Hunt"],
    theme: "Color Hunt",
    tpk_fields: tpkFields,
    field_icons: {
      "Nama Pelanggan": "person",
      "Keterangan Barang": "box",
      "No. Faktur": "hash",
      "Tgl Faktur": "calendar",
      "Kuantitas": "hash",
      "Harga Satuan": "tag",
      "Unit 1 Barang": "box",
    },
    out_cols: [
      ["No", 52, "center"],
      ["Nama Pelanggan", 160, "left"],
      ["Keterangan Barang", 280, "left"],
      ["No. Faktur", 130, "center"],
      ["Tgl Faktur", 100, "center"],
      ["Kuantitas", 78, "right"],
      ["Harga Satuan", 100, "right"],
      ["Unit", 52, "center"],
      ["Harga Jual", 118, "right"],
      ["Diskon", 108, "right"],
      ["DPP", 118, "right"],
      ["DPP Nilai Lain", 128, "right"],
      ["Tarif PPN", 72, "center"],
      ["PPN", 118, "right"],
      ["Tarif PPnBM", 82, "center"],
      ["PPnBM", 78, "right"],
    ],
    faktur_cols: [
      ["Baris", 52, "center"],
      ["Tgl Faktur", 100, "center"],
      ["No. Faktur", 130, "center"],
      ["Nama Pembeli", 198, "left"],
      ["NPWP/NIK Pembeli", 138, "center"],
    ],
    det_cols: [
      ["Baris", 52, "center"],
      ["Nama Barang / Jasa", 298, "left"],
      ["Harga Satuan", 98, "right"],
      ["Jumlah", 78, "right"],
      ["DPP", 118, "right"],
      ["PPN", 118, "right"],
    ],
    dup_colors: [["#C9996B", "#E6D2BF"], ["#5C766D", "#D9E2DD"], ["#A65F55", "#F1D9D4"]],
    detail_opt_choices: ["A - Barang", "B - Jasa"],
    detail_unit_choices: ["UM.0021 - Piece", "UM.0018 - Unit", "UM.0017 - Lusin"],
    detail_opt_labels: { A: "Barang", B: "Jasa" },
    detail_unit_labels: { "UM.0021": "Piece", "UM.0018": "Unit", "UM.0017": "Lusin" },
    templates: {},
    db_penjual: {},
    db_pembeli: {},
    dlm_fields: dlmFields,
    dlm_field_icons: { "No. Faktur": "hash", "Tgl Faktur": "calendar", "Nama Pemasok": "person", "Nilai Faktur": "tag" },
    dlm_out_cols: [
      ["No", 50, "center"],
      ["No. Dokumen", 150, "left"],
      ["Tgl Dokumen", 100, "center"],
      ["Jenis Transaksi", 130, "center"],
      ["Detail Transaksi", 170, "left"],
      ["Dokumen", 130, "center"],
      ["Masa", 70, "center"],
      ["Tahun", 70, "center"],
      ["DPP (Tax Base)", 118, "right"],
      ["PPN (VAT)", 110, "right"],
      ["PPnBM", 110, "right"],
      ["NPWP Pemasok", 138, "center"],
      ["Nama Pemasok", 180, "left"],
    ],
    dlm_trx_type_choices: ["04 - PURCHASE"],
    dlm_trx_detail_choices: ["01 - To other party than VAT Collector"],
    dlm_trx_doc_choices: ["8 - Special documents"],
    dlm_trx_type_labels: { "04": "PURCHASE" },
    dlm_trx_detail_labels: { "01": "To other party than VAT Collector" },
    dlm_trx_doc_labels: { "8": "Special documents" },
    db_pemasok: {},
    dlm_templates: {},
    sdl_out_cols: [["No", 50, "center"], ["BuyerName", 180, "left"], ["TransactionDate", 110, "center"], ["VAT", 120, "right"]],
    sdl_trx_code_choices: ["Normal - Untuk Lampiran I.A.5"],
    sdl_trx_code_labels: { Normal: "Untuk Lampiran I.A.5" },
    sdl_buyer_id_choices: ["NPWP - Nomor Pokok Wajib Pajak", "NIK - Nomor Induk Kependudukan"],
    sdl_buyer_id_labels: { NPWP: "Nomor Pokok Wajib Pajak", NIK: "Nomor Induk Kependudukan" },
    sdl_good_service_choices: ["A - Barang", "B - Jasa"],
    sdl_good_service_labels: { A: "Barang", B: "Jasa" },
    state: emptyState(),
  };
}
